/* Cashual enhancements: all records remain local to this browser. */
const $c=s=>document.querySelector(s),escC=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=n=>`₱${Math.abs(+n||0).toLocaleString('en-PH',{maximumFractionDigits:2})}`;
const currentDay=()=>new Date().toISOString().slice(0,10),currentMonth=()=>currentDay().slice(0,7);
state.loans??=[];state.homeSections={cashflow:true,spending:true,activity:true,wallets:true,bills:true,...state.homeSections};
state.walletCompact??=false;
state.categories.forEach(c=>{c.id??=crypto.randomUUID();c.parent??=''});
state.wallets.forEach(w=>{w.id??=crypto.randomUUID();w.color=/^#[0-9a-f]{6}$/i.test(w.color||'')?w.color:'#d7f36a'});
state.transactions.forEach(t=>{t.walletId??=state.wallets.find(w=>w.name===t.wallet)?.id||'';t.time??='12:00';t.isoDate??=currentDay()});save();
let selectedWallet='',selectedMonth=currentMonth(),editRecord=null;
const iconExtras={loan:'<path d="M4 8h16v12H4zM8 8V5h8v3M8 14h8"/>',coffee:'<path d="M4 6h13v8a6.5 6.5 0 0 1-13 0zM17 7h2a3 3 0 0 1 0 6h-2M4 20h15"/>',heart:'<path d="M12 21 3 12a5 5 0 0 1 7-7l2 2 2-2a5 5 0 0 1 7 7z"/>',bolt:'<path d="m13 2-9 12h7l-1 8 10-12h-7z"/>',book:'<path d="M3 4h8a3 3 0 0 1 3 3v14H6a3 3 0 0 0-3 0zM21 4h-4a3 3 0 0 0-3 3v14h4a3 3 0 0 1 3 0z"/>',gift:'<rect x="3" y="9" width="18" height="12"/><path d="M12 9v12M3 13h18M12 9C5 9 5 3 9 3c3 0 3 6 3 6zm0 0c7 0 7-6 3-6-3 0-3 6-3 6z"/>'};Object.assign(icons,iconExtras);
nav.splice(4,0,['loans','loan','Loans']);
const txWallet=t=>state.wallets.find(w=>w.id===t.walletId||w.name===t.wallet);
const txCategory=t=>state.categories.find(c=>c.id===t.categoryId||c.name===t.category);
const monthEntries=(type)=>state.transactions.filter(t=>t.isoDate?.startsWith(selectedMonth)&&(!type||t.type===type));
const monthStats=()=>{let tx=monthEntries(),income=tx.filter(t=>t.type==='income').reduce((a,t)=>a+ +t.amount,0),expenses=tx.filter(t=>t.type==='expense').reduce((a,t)=>a+Math.abs(+t.amount),0);return{income,expenses,saved:income-expenses}};
function categoryPie(){let m=new Map();monthEntries('expense').forEach(t=>{let c=txCategory(t),key=c?.id||t.category||'Other',x=m.get(key)||{name:c?.name||t.category||'Other',color:c?.color||'#9ca39a',icon:c?.icon||'circle',amount:0};x.amount+=Math.abs(+t.amount);m.set(key,x)});let arr=[...m.values()].sort((a,b)=>b.amount-a.amount),sum=arr.reduce((a,x)=>a+x.amount,0);if(!sum)return '<div class="empty">No expenses this month</div>';let from=0,gradient=arr.map(x=>{let start=from;from+=x.amount/sum*100;return `${x.color} ${start}% ${from}%`}).join(',');return `<div class="pie-layout"><div class="pie" style="background:conic-gradient(${gradient})"><div><strong>${cash(sum)}</strong><small>Total spent</small></div></div><div class="pie-legend">${arr.map(x=>`<div><span style="background:${x.color}">${userIcon(x.icon)}</span><strong>${escC(x.name)}</strong><b>${cash(x.amount)}</b></div>`).join('')}</div></div>`}
const oldWalletCard=walletCard;walletCard=function(w){return `<button class="card wallet custom-wallet wallet-link ${state.walletCompact?'compact-wallet':''}" data-wallet-view="${escC(w.id)}" style="--wallet-bg:${escC(w.color)};--accent:${escC(w.accent||'#171b16')}">${w.image?`<img class="wallet-image" src="${w.image}" alt="">`:`<span class="wallet-icon">${userIcon(w.icon||'wallet')}</span>`}<div class="wallet-name">${escC(w.name)}</div><div class="wallet-amount money">${cash(w.balance)}</div><small>${escC(w.type)} · View summary</small></button>`};
wallets=function(){let a=state.wallets.filter(w=>!w.archived);return `<section><div class="page-head"><div><h2>Wallets</h2><p>Select a wallet to see its balance, activity, and QR code.</p></div><div class="action-pair"><button class="ghost-btn" data-open="transfer">Transfer</button><button class="primary-btn" data-open="wallet">Add wallet</button></div></div>${a.length?`<div class="grid wallet-strip manage-wallets">${a.map(walletCard).join('')}</div>`:`<div class="card empty">No wallets yet <button class="primary-btn" data-open="wallet">Add first wallet</button></div>`}</section>`};
function walletView(){let w=state.wallets.find(x=>x.id===selectedWallet);if(!w)return wallets();let entries=state.transactions.filter(t=>t.walletId===w.id||t.wallet===w.name||t.fromId===w.id||t.toId===w.id),income=entries.filter(t=>t.type==='income').reduce((a,t)=>a+ +t.amount,0),expenses=entries.filter(t=>t.type==='expense').reduce((a,t)=>a+Math.abs(+t.amount),0);return `<section><button class="text-btn" data-route="wallets">← All wallets</button><div class="wallet-detail-grid">${walletCard(w)}<div class="card wallet-summary"><h2>${escC(w.name)}</h2><p>${escC(w.type)} · ${w.included?'Included':'Excluded'} in net balance</p><div class="cashflow-stats"><div><span>Balance</span><strong>${cash(w.balance)}</strong></div><div><span>Income</span><strong>${cash(income)}</strong></div><div><span>Expenses</span><strong>${cash(expenses)}</strong></div></div><div class="detail-actions"><button class="ghost-btn" data-wallet-edit="${w.id}">Edit wallet</button><button class="ghost-btn" data-open="transfer">Transfer</button><button class="ghost-btn" data-wallet-archive="${w.id}">Archive</button></div></div></div>${w.qr?`<div class="card qr-card"><h2>Wallet QR code</h2><img src="${w.qr}" alt="QR code for ${escC(w.name)}"></div>`:''}<div class="card transactions home-section"><div class="card-head"><h2>Activity</h2><span>${entries.length} entries</span></div>${txRows(entries)}</div></section>`}
function loanPage(){let owed=state.loans.filter(x=>x.direction==='owed'&&!x.settled).reduce((a,x)=>a+ +x.amount,0),owe=state.loans.filter(x=>x.direction==='owe'&&!x.settled).reduce((a,x)=>a+ +x.amount,0);return `<section><div class="page-head"><div><h2>Loans</h2><p>Track money owed to you and money you owe.</p></div><button class="primary-btn" data-enhance-form="loan">Add loan</button></div><div class="cashflow-stats card"><div><span>Owed to you</span><strong>${cash(owed)}</strong></div><div><span>You owe</span><strong>${cash(owe)}</strong></div></div><div class="loan-list">${state.loans.length?state.loans.map(l=>`<div class="card loan-item"><div class="tx-icon">${svg('loan')}</div><div><strong>${escC(l.person)}</strong><small>${l.direction==='owed'?'Owes you':'You owe'} · ${escC(state.wallets.find(w=>w.id===l.walletId)?.name||'No wallet')}</small></div><strong>${cash(l.amount)}</strong><span>${l.settled?'Settled':'Open'}</span><button class="text-btn" data-loan-edit="${l.id}">Edit</button><button class="text-btn" data-loan-settle="${l.id}">${l.settled?'Reopen':'Settle'}</button></div>`).join(''):'<div class="card empty">No loans yet</div>'}</div></section>`}
const oldHome=home;home=function(){let m=monthStats(),a=state.wallets.filter(w=>!w.archived),balance=a.filter(w=>w.included).reduce((s,w)=>s+ +w.balance,0),opts=state.homeSections;return `<section class="grid dashboard-grid"><article class="balance-card"><div class="card-label">Net balance</div><div class="balance money">${cash(balance)}</div><div class="balance-row"><div class="metric"><span>Monthly income</span><strong>${cash(m.income)}</strong></div><div class="metric"><span>Expenses</span><strong>${cash(m.expenses)}</strong></div><div class="metric"><span>Net saved</span><strong>${m.saved<0?'−':''}${cash(m.saved)}</strong></div></div></article><article class="card"><div class="card-head"><h2>Quick access</h2></div><div class="home-shortcuts"><button data-route="wallets">${svg('wallet')} Wallets</button><button data-route="bills">${svg('receipt')} Bills</button><button data-route="loans">${svg('loan')} Loans</button><button data-route="transactions">${svg('transactions')} Expenses</button></div></article></section>${!a.length?`<section class="start-card">${svg('wallet')}<div><h2>Start with a wallet</h2><p>Connect your first balance to begin.</p></div><button class="primary-btn" data-open="wallet">Add wallet</button></section>`:''}${opts.cashflow?`<section class="card home-section"><div class="card-head"><h2>Monthly cash flow</h2><input class="month-picker" type="month" value="${selectedMonth}"></div><div class="cashflow-stats"><div><span>Income</span><strong>${cash(m.income)}</strong></div><div><span>Expenses</span><strong>${cash(m.expenses)}</strong></div><div><span>Net saved</span><strong>${m.saved<0?'−':''}${cash(m.saved)}</strong></div></div></section>`:''}${opts.spending?`<section class="card home-section"><div class="card-head"><h2>Expenses by category</h2><span>${selectedMonth}</span></div>${categoryPie()}</section>`:''}${opts.activity?`<section class="card home-section transactions"><div class="card-head"><h2>Recent activity</h2><button class="text-btn" data-route="transactions">View all</button></div>${txRows(state.transactions.slice(0,5))}</section>`:''}${opts.wallets&&a.length?`<section class="home-section"><div class="card-head"><h2>Wallets</h2><button class="text-btn" data-route="wallets">View all</button></div><div class="grid wallet-strip">${a.slice(0,3).map(walletCard).join('')}</div></section>`:''}${opts.bills?`<section class="card home-section"><div class="card-head"><h2>Bills</h2><button class="text-btn" data-route="bills">View all</button></div>${state.bills.length?state.bills.slice(0,3).map(b=>`<div class="event"><strong>${escC(b.name)}</strong><span>${cash(b.amount)}</span></div>`).join(''):'<div class="empty">No bills yet</div>'}</section>`:''}`};
insights=function(){let m=monthStats();return `<section><div class="page-head"><div><h2>Insights</h2><p>Based on your recorded transactions.</p></div><input class="month-picker" type="month" value="${selectedMonth}"></div><div class="cashflow-stats card"><div><span>Income</span><strong>${cash(m.income)}</strong></div><div><span>Expenses</span><strong>${cash(m.expenses)}</strong></div><div><span>Net saved</span><strong>${m.saved<0?'−':''}${cash(m.saved)}</strong></div></div><article class="card home-section"><div class="card-head"><h2>Expense mix</h2></div>${categoryPie()}</article></section>`};
more=function(){return `<section class="settings-page"><div class="page-head"><div><h2>Settings</h2><p>Personalize your dashboard and manage data.</p></div></div><button class="profile-setting card" data-edit-profile><span class="profile-avatar">${getInitials()}</span><div><strong>${escC(userProfile.name||'Your profile')}</strong><small>${userProfile.salary?`Monthly salary · ${cash(userProfile.salary)}`:'Optional salary not set'}</small></div><span class="edit-label">Edit</span></button><details class="card settings-block" open><summary>Home display</summary><div class="toggle-grid">${[['cashflow','Monthly cash flow'],['spending','Expense pie chart'],['activity','Recent activity'],['wallets','Wallets'],['bills','Bills']].map(([k,t])=>`<label><input type="checkbox" data-home-toggle="${k}" ${state.homeSections[k]?'checked':''}> ${t}</label>`).join('')}</div></details><details class="card settings-block" open><summary>Categories & subcategories</summary><div class="category-grid">${state.categories.map(c=>`<button class="category-pill" data-category-edit="${c.id}"><span style="background:${escC(c.color)}">${userIcon(c.icon)}</span><strong>${escC(c.name)}</strong>${c.parent?`<small>in ${escC(state.categories.find(x=>x.id===c.parent)?.name||'Other')}</small>`:''}</button>`).join('')}</div><button class="ghost-btn settings-action" data-enhance-form="category">Add category</button></details><details class="card settings-block" open><summary>Import & export</summary><p>CSV exports wallets, transactions, categories, bills, and loans. Keep this file private.</p><div class="settings-actions"><button class="ghost-btn" data-export>Export CSV</button><label class="ghost-btn file-label">Import CSV<input id="csvImport" type="file" accept=".csv,text/csv" hidden></label></div></details><details class="card settings-block"><summary>Appearance & privacy</summary><div class="settings-actions"><button class="ghost-btn" data-theme-setting>Toggle dark mode</button><button class="ghost-btn" data-privacy-setting>Hide/show balances</button></div></details></section>`};
const settingsBase=more;more=function(){return settingsBase().replace('<details class="card settings-block" open>',`<details class="card settings-block" open><summary>Wallet display</summary><div class="toggle-grid"><label><input type="checkbox" data-wallet-compact ${state.walletCompact?'checked':''}> Compact wallet cards</label></div></details><details class="card settings-block" open>`)};
const oldRender=render;render=function(){let r=location.hash.slice(1)||'home';if(r==='wallet-detail'){oldRender();pageTitle.textContent='Wallet details';view.innerHTML=walletView()}else if(r==='loans'){oldRender();pageTitle.textContent='Loans';view.innerHTML=loanPage()}else oldRender();const n=`<button class="nav-item ${r==='loans'?'active':''}" data-route="loans"><span>${svg('loan')}</span>Loans</button>`;if(!desktopNav.querySelector('[data-route="loans"]'))desktopNav.insertAdjacentHTML('beforeend',n);if(!mobileNav.querySelector('[data-route="loans"]'))mobileNav.insertAdjacentHTML('beforeend',n)};
function field(label,name,type='text',value='',extra=''){return `<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${escC(value)}" ${extra}></label>`}function select(label,name,items,value=''){return `<label class="field"><span>${label}</span><select name="${name}">${items.map(([v,t])=>`<option value="${escC(v)}" ${String(v)===String(value)?'selected':''}>${escC(t)}</option>`).join('')}</select></label>`}const walletChoices=()=>state.wallets.filter(w=>!w.archived).map(w=>[w.id,w.name]);
function enhanceForm(kind,id=''){if(quickDialog.open)quickDialog.close();editRecord={kind,id};let x=kind==='wallet'?state.wallets.find(y=>y.id===id):kind==='category'?state.categories.find(y=>y.id===id):kind==='loan'?state.loans.find(y=>y.id===id):state.transactions.find(y=>String(y.id)===String(id));formDialog.dataset.kind=kind;formOverline.textContent=id?'Edit':'New';formTitle.textContent=kind[0].toUpperCase()+kind.slice(1);saveBtn.textContent=id?'Save changes':'Save';let w=walletChoices(),f='';if(kind==='wallet')f=field('Name','name','text',x?.name,'required')+select('Type','type',['Cash','Bank','E-wallet','Savings','Credit card','Other'].map(t=>[t,t]),x?.type)+field('Current balance','amount','number',x?.balance??0,'required min="0" step="0.01"')+field('Emoji or symbol','icon','text',x?.icon||'💳','maxlength="8"')+field('Background','color','color',/^#[0-9a-f]{6}$/i.test(x?.color||'')?x.color:'#d7f36a')+field('Accent','accent','color',x?.accent||'#171b16')+'<label class="field"><span>Wallet image</span><input name="image" type="file" accept="image/*"></label><label class="field"><span>QR code image (optional)</span><input name="qr" type="file" accept="image/*"></label>'+`<label class="field check-field"><input name="included" type="checkbox" ${x?.included!==false?'checked':''}> Include in net balance</label>`;else if(kind==='category')f=field('Name','name','text',x?.name,'required')+select('Parent category','parent',[['','Top-level'],...state.categories.filter(c=>c.id!==id&&!c.parent).map(c=>[c.id,c.name])],x?.parent)+field('Emoji or icon','icon','text',x?.icon||'⭐','maxlength="8"')+field('Color','color','color',x?.color||'#d7f36a');else if(kind==='loan')f=select('Direction','direction',[['owed','Owed to me'],['owe','I owe']],x?.direction)+field('Person','person','text',x?.person,'required')+field('Amount','amount','number',x?.amount,'required min="0.01" step="0.01"')+select('Related wallet','walletId',[['','None'],...w],x?.walletId)+field('Date','date','date',x?.date||currentDay())+field('Note','note','text',x?.note||'');else f=field('Amount','amount','number',Math.abs(x?.amount||0)||'','required min="0.01" step="0.01"')+field('Purchase or source','name','text',x?.title,'required')+select('Wallet','walletId',w,x?.walletId||w[0]?.[0])+select('Category','categoryId',state.categories.map(c=>[c.id,`${c.parent?'↳ ':''}${c.name}`]),x?.categoryId||state.categories.find(c=>c.name===x?.category)?.id)+field('Date','date','date',x?.isoDate||currentDay())+field('Time','time','time',x?.time||new Date().toTimeString().slice(0,5))+field('Note','note','text',x?.note||'');formFields.innerHTML=`<div class="form-grid compact-form">${f}</div>`;formDialog.showModal()}
function fileData(file){return new Promise(resolve=>{if(!file?.size)return resolve(null);if(file.size>2e6)return resolve('large');let r=new FileReader;r.onload=()=>resolve(r.result);r.onerror=()=>resolve(null);r.readAsDataURL(file)})}
const oldSubmit=entryForm.onsubmit;entryForm.onsubmit=async e=>{if(!editRecord)return oldSubmit(e);e.preventDefault();let {kind,id}=editRecord,f=new FormData(entryForm),d=Object.fromEntries(f);if(kind==='wallet'){let w=state.wallets.find(y=>y.id===id),image=await fileData(f.get('image')),qr=await fileData(f.get('qr'));if(image==='large'||qr==='large')return toastMsg('Images must be under 2 MB');let old=w?.name,data={name:d.name.trim(),type:d.type,balance:+d.amount,icon:d.icon||'wallet',color:d.color,accent:d.accent,included:!!d.included};if(w){Object.assign(w,data);if(image)w.image=image;if(qr)w.qr=qr;state.transactions.forEach(t=>{if(t.wallet===old)t.wallet=w.name})}else state.wallets.push({id:crypto.randomUUID(),...data,image,qr,archived:false})}else if(kind==='category'){let c=state.categories.find(y=>y.id===id),data={name:d.name.trim(),parent:d.parent||'',icon:d.icon||'circle',color:d.color};if(c)Object.assign(c,data);else state.categories.push({id:crypto.randomUUID(),...data})}else if(kind==='loan'){let l=state.loans.find(y=>y.id===id),data={direction:d.direction,person:d.person.trim(),amount:+d.amount,walletId:d.walletId,date:d.date,note:d.note,settled:l?.settled||false};if(l)Object.assign(l,data);else state.loans.unshift({id:crypto.randomUUID(),...data})}else{let t=state.transactions.find(y=>String(y.id)===String(id)),w=state.wallets.find(y=>y.id===d.walletId),a=(kind==='expense'?-1:1)* +d.amount;if(t){let old=txWallet(t);if(old)old.balance-= +t.amount;w.balance+=a;Object.assign(t,{title:d.name.trim(),amount:a,walletId:w.id,wallet:w.name,categoryId:d.categoryId,category:state.categories.find(c=>c.id===d.categoryId)?.name,isoDate:d.date,time:d.time,note:d.note})}else{w.balance+=a;state.transactions.unshift({id:crypto.randomUUID(),type:kind,title:d.name.trim(),amount:a,walletId:w.id,wallet:w.name,categoryId:d.categoryId,category:state.categories.find(c=>c.id===d.categoryId)?.name,isoDate:d.date,time:d.time,note:d.note})}}try{save()}catch{return toastMsg('Storage is full; try smaller images')}editRecord=null;formDialog.close();render();toastMsg('Saved')};
const priorOpen=openForm;openForm=function(kind){if(['wallet','category','expense','income'].includes(kind)){if(['expense','income'].includes(kind)&&!walletChoices().length){toastMsg('Add a wallet first');return enhanceForm('wallet')}return enhanceForm(kind)}return priorOpen(kind)};
const incomeDefaults=[['Salary','income-salary'],['Allowance','income-allowance'],['Freelance','income-freelance'],['Business','income-business'],['Gift','income-gift'],['Bonus','income-bonus'],['Refund','income-refund'],['Interest','income-interest'],['Other income','income-other']];for(const [name,id] of incomeDefaults)if(!state.categories.some(c=>c.id===id))state.categories.push({id,name,icon:'income',color:'#79b89b',parent:'',group:'income'});save();
const baseEnhancedForm=enhanceForm;enhanceForm=function(kind,id=''){if(kind==='transfer'){if(quickDialog.open)quickDialog.close();let choices=walletChoices();if(choices.length<2){toastMsg('Add two wallets to transfer');return enhanceForm('wallet')}editRecord={kind,id};formDialog.dataset.kind='transfer';formOverline.textContent='New transfer';formTitle.textContent='Transfer between wallets';saveBtn.textContent='Transfer';formFields.innerHTML=`<div class="form-grid compact-form">${select('From wallet','from',choices)}${select('To wallet','to',choices,choices[1][0])}${field('Amount','amount','number','','required min="0.01" step="0.01"')}${field('Transfer fee (optional)','fee','number','0','min="0" step="0.01"')}${field('Date','date','date',currentDay())}${field('Time','time','time',new Date().toTimeString().slice(0,5))}${field('Note','note')}</div>`;formDialog.showModal();return}baseEnhancedForm(kind,id);if(kind==='income'||kind==='expense'){let choices=state.categories.filter(c=>kind==='income'?c.group==='income':c.group!=='income'),picker=formFields.querySelector('[name="categoryId"]');if(picker)picker.innerHTML=choices.map(c=>`<option value="${escC(c.id)}" ${c.id===state.transactions.find(t=>String(t.id)===String(id))?.categoryId?'selected':''}>${escC(c.name)}</option>`).join('')}if(kind==='category'){let c=state.categories.find(x=>x.id===id);formFields.querySelector('.compact-form')?.insertAdjacentHTML('beforeend',select('Used for','group',[['expense','Expenses'],['income','Money received']],c?.group||'expense'))}};
const categoryAwareForm=enhanceForm;enhanceForm=function(kind,id=''){categoryAwareForm(kind,id);if(kind==='wallet'){let second=formFields.querySelector('[name="accent"]')?.closest('label')?.querySelector('span');if(second)second.textContent='Second color'}};
openForm=function(kind){if(['wallet','category','expense','income','transfer'].includes(kind)){if(['expense','income'].includes(kind)&&!walletChoices().length){toastMsg('Add a wallet first');return enhanceForm('wallet')}return enhanceForm(kind)}editRecord=null;return priorOpen(kind)};
const submitEnhanced=entryForm.onsubmit;entryForm.onsubmit=async e=>{if(editRecord?.kind==='transfer'){e.preventDefault();let d=Object.fromEntries(new FormData(entryForm)),from=state.wallets.find(w=>w.id===d.from),to=state.wallets.find(w=>w.id===d.to),amount=+d.amount,fee=+d.fee||0;if(!from||!to||from.id===to.id)return toastMsg('Choose two different wallets');if(!Number.isFinite(amount)||amount<=0||!Number.isFinite(fee)||fee<0)return toastMsg('Enter a valid amount');if(from.balance<amount+fee)return toastMsg('Not enough balance in the source wallet');from.balance-=amount+fee;to.balance+=amount;const transferId=crypto.randomUUID();state.transactions.unshift({id:transferId,type:'transfer',title:`${from.name} → ${to.name}`,amount:-amount,fromId:from.id,toId:to.id,walletId:from.id,wallet:from.name,category:'Transfer',isoDate:d.date,time:d.time,note:d.note||'',fee});if(fee)state.transactions.unshift({id:crypto.randomUUID(),type:'expense',title:'Transfer fee',amount:-fee,walletId:from.id,wallet:from.name,category:'Fees',isoDate:d.date,time:d.time,transferId});save();editRecord=null;formDialog.close();render();toastMsg('Transfer saved');return}const group=editRecord?.kind==='category'?new FormData(entryForm).get('group'):null,id=editRecord?.id;await submitEnhanced(e);if(group){let category=id?state.categories.find(c=>c.id===id):state.categories.at(-1);if(category){category.group=group;save();render()}}};
function csvQuote(v){let s=String(v??'');return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}function exportCsv(){let rows=[];for(const [type,items] of [['wallet',state.wallets],['transaction',state.transactions],['category',state.categories],['bill',state.bills],['loan',state.loans]])items.forEach(item=>{let copy={...item};delete copy.image;delete copy.qr;rows.push([type,JSON.stringify(copy)])});let blob=new Blob(['type,data\r\n'+rows.map(r=>r.map(csvQuote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`cashual-${currentDay()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}function csvRows(s){let out=[],row=[],cell='',q=false;for(let i=0;i<s.length;i++){let c=s[i];if(q){if(c==='"'&&s[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));out.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);out.push(row)}return out}async function importCsv(file){if(!file)return;let rows=csvRows(await file.text()),header=rows.shift();if(header?.[0]!=='type'||header?.[1]!=='data')return toastMsg('Use a Cashual CSV export');let next=structuredClone(state),types={wallet:'wallets',transaction:'transactions',category:'categories',bill:'bills',loan:'loans'},count=0;try{for(let row of rows){let key=types[row[0]];if(!key)continue;let record=JSON.parse(row[1]);if(!record?.id)continue;let pos=next[key].findIndex(x=>String(x.id)===String(record.id));if(pos<0)next[key].push(record);else next[key][pos]=record;count++}}catch{return toastMsg('Invalid CSV data')}state=next;save();render();toastMsg(`Imported ${count} records`)}
document.addEventListener('click',e=>{let b=e.target.closest('[data-wallet-view],[data-wallet-edit],[data-wallet-archive],[data-enhance-form],[data-category-edit],[data-loan-edit],[data-loan-settle],[data-export],[data-theme-setting],[data-privacy-setting],[data-edit-tx]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.walletView){selectedWallet=b.dataset.walletView;location.hash='wallet-detail';render()}else if(b.dataset.walletEdit)enhanceForm('wallet',b.dataset.walletEdit);else if(b.dataset.walletArchive){let w=state.wallets.find(x=>x.id===b.dataset.walletArchive);w.archived=true;save();location.hash='wallets';render()}else if(b.dataset.enhanceForm)enhanceForm(b.dataset.enhanceForm);else if(b.dataset.categoryEdit)enhanceForm('category',b.dataset.categoryEdit);else if(b.dataset.loanEdit)enhanceForm('loan',b.dataset.loanEdit);else if(b.dataset.loanSettle){let l=state.loans.find(x=>x.id===b.dataset.loanSettle);l.settled=!l.settled;save();render()}else if(b.dataset.editTx){let t=state.transactions.find(x=>String(x.id)===String(b.dataset.editTx));if(t?.type==='transfer')toastMsg('Transfers are read-only');else if(t)enhanceForm(t.type,t.id)}else if(b.dataset.export!==undefined)exportCsv();else if(b.dataset.themeSetting!==undefined)themeBtn.click();else if(b.dataset.privacySetting!==undefined)privacyBtn.click()},true);
document.addEventListener('change',e=>{if(e.target.dataset.homeToggle){state.homeSections[e.target.dataset.homeToggle]=e.target.checked;save()}if(e.target.dataset.walletCompact!==undefined){state.walletCompact=e.target.checked;save();render()}if(e.target.classList.contains('month-picker')){selectedMonth=e.target.value;render()}if(e.target.id==='csvImport')importCsv(e.target.files[0])});
document.addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(!b)return;location.hash=b.dataset.route;if(b.dataset.route==='loans'||b.dataset.route==='wallets')setTimeout(render,0)});
window.addEventListener('hashchange',()=>setTimeout(render,0));render();

// Wallet layout, loan bookkeeping, and interest are kept local with the rest of Cashual's data.
state.walletLayout ||= state.walletCompact ? 'line' : 'grid';
const cashualPlus = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>';
const cashualIconButton = (kind,label,icon) => `<button class="icon-action ${kind==='wallet'?'primary-btn':'ghost-btn'}" data-open="${kind}" aria-label="${label}" title="${label}">${icon}</button>`;
const walletPageBeforeLayout = wallets;
wallets = function(){
  return walletPageBeforeLayout()
    .replace('<button class="ghost-btn" data-open="transfer">Transfer</button>',cashualIconButton('transfer','Transfer between wallets',svg('transfer')))
    .replace('<button class="primary-btn" data-open="wallet">Add wallet</button>',cashualIconButton('wallet','Add wallet',cashualPlus))
    .replace('class="grid wallet-strip manage-wallets"',`class="grid wallet-strip manage-wallets ${state.walletLayout==='line'?'line-view':'grid-view'}"`);
};
const walletViewBeforeInterest = walletView;
walletView = function(){
  const w=state.wallets.find(x=>x.id===selectedWallet), html=walletViewBeforeInterest();
  if(!w)return html;
  const interest=w.interest;
  const panel=`<div class="card interest-panel home-section"><div><h2>Wallet interest</h2><p>${interest?.enabled?`${escC(interest.rate)}% ${escC(interest.frequency)} · next credit ${escC(nextInterestDate(interest.lastApplied,interest.frequency))}`:'No automatic interest set'}</p></div><button class="ghost-btn" data-interest-wallet="${escC(w.id)}">${interest?'Edit interest':'Add interest'}</button></div>`;
  return html.replace('<button class="ghost-btn" data-open="transfer">Transfer</button>',cashualIconButton('transfer','Transfer from this wallet',svg('transfer')))
    .replace('<div class="card transactions home-section">',panel+'<div class="card transactions home-section">');
};
const settingsBeforeLayout=more;
more=function(){return settingsBeforeLayout().replace(/<details class="card settings-block" open><summary>Wallet display<\/summary>[\s\S]*?<\/details>/,`<details class="card settings-block" open><summary>Wallet display</summary><div class="toggle-grid"><label><input type="radio" name="walletLayout" value="grid" ${state.walletLayout==='grid'?'checked':''}> Grid cards</label><label><input type="radio" name="walletLayout" value="line" ${state.walletLayout==='line'?'checked':''}> Compact lines</label></div></details>`)};
function nextInterestDate(last,frequency){const d=new Date((last||currentDay())+'T12:00:00');if(Number.isNaN(+d))return currentDay();const day=d.getDate();if(frequency==='weekly')d.setDate(day+7);else if(frequency==='monthly'){d.setDate(1);d.setMonth(d.getMonth()+1);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()))}else if(frequency==='yearly'){d.setDate(1);d.setFullYear(d.getFullYear()+1);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()))}else d.setDate(day+1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function applyWalletInterest(){let changed=false,today=currentDay();for(const w of state.wallets){const i=w.interest;if(!i?.enabled||!Number.isFinite(+i.rate)||+i.rate<=0)continue;let due=nextInterestDate(i.lastApplied,i.frequency),count=0;while(due<=today&&count++<366){const amount=Math.round(Math.max(0,+w.balance)*(+i.rate/100)*100)/100;if(amount>0){w.balance+=amount;state.transactions.unshift({id:crypto.randomUUID(),type:'income',title:'Wallet interest',amount,walletId:w.id,wallet:w.name,categoryId:'income-interest',category:'Interest',isoDate:due,time:'12:00',note:`${i.rate}% ${i.frequency} interest`})}i.lastApplied=due;changed=true;due=nextInterestDate(due,i.frequency)}}if(changed){save();render()}}
const interestBaseForm=enhanceForm;
enhanceForm=function(kind,id=''){
  if(kind==='interest'){
    const w=state.wallets.find(x=>x.id===id);if(!w)return;
    if(quickDialog.open)quickDialog.close();editRecord={kind,id};formDialog.dataset.kind=kind;formOverline.textContent='Wallet';formTitle.textContent=`Interest · ${w.name}`;saveBtn.textContent='Save interest';
    const i=w.interest||{};
    formFields.innerHTML=`<div class="form-grid compact-form">${field('Interest per period (%)','rate','number',i.rate??0,'required min="0" max="100" step="0.001"')}${select('Frequency','frequency',[['daily','Daily'],['weekly','Weekly'],['monthly','Monthly'],['yearly','Yearly']],i.frequency||'monthly')}<label class="field check-field full"><input name="enabled" type="checkbox" ${i.enabled?'checked':''}> Enable automatic interest</label><p class="form-hint full">Credits compound on the wallet balance when Cashual is opened after each due date. This is a percentage per selected period, not an annualized rate.</p></div>`;
    formDialog.showModal();return;
  }
  interestBaseForm(kind,id);
  if(kind==='loan'){
    const l=state.loans.find(x=>x.id===id);
    formFields.querySelector('.compact-form')?.insertAdjacentHTML('beforeend',`<label class="field check-field full"><input name="moveFunds" type="checkbox" ${l?.funded?'checked':''} ${l?.funded?'disabled':''}> Record the initial loan movement in the related wallet</label><p class="form-hint full">${l?.funded?'Already recorded; wallet movement cannot be changed here.':'Optional. Lending subtracts from the wallet; borrowing adds to it.'}</p>`);
  }
};
const interestBaseSubmit=entryForm.onsubmit;
entryForm.onsubmit=async e=>{
  if(editRecord?.kind==='interest'){
    e.preventDefault();const w=state.wallets.find(x=>x.id===editRecord.id),d=Object.fromEntries(new FormData(entryForm)),rate=+d.rate;
    if(!w||!Number.isFinite(rate)||rate<0||rate>100)return toastMsg('Enter a rate from 0 to 100%');
    const old=w.interest,enabled=!!d.enabled;
    w.interest={rate,frequency:d.frequency,enabled,lastApplied:old?.enabled&&enabled&&old.frequency===d.frequency?old.lastApplied:currentDay()};
    save();editRecord=null;formDialog.close();render();toastMsg('Interest settings saved');return;
  }
  if(editRecord?.kind==='loan'){
    e.preventDefault();const {id}=editRecord,d=Object.fromEntries(new FormData(entryForm)),existing=state.loans.find(x=>x.id===id),wallet=state.wallets.find(x=>x.id===d.walletId),amount=+d.amount;
    if(!d.person?.trim()||!Number.isFinite(amount)||amount<=0)return toastMsg('Enter a person and valid amount');
    if(existing?.funded&&(existing.amount!==amount||existing.walletId!==d.walletId||existing.direction!==d.direction))return toastMsg('Recorded loan amount, wallet, and direction cannot be edited');
    if(d.moveFunds&&!wallet)return toastMsg('Choose a related wallet to record funds');
    if(d.moveFunds&&!existing?.funded&&d.direction==='owed'&&wallet.balance<amount)return toastMsg('Not enough balance in the wallet');
    const data={direction:d.direction,person:d.person.trim(),amount,walletId:d.walletId||'',date:d.date||currentDay(),note:d.note||'',settled:existing?.settled||false,funded:existing?.funded||!!d.moveFunds};
    const loan=existing||{id:crypto.randomUUID()};Object.assign(loan,data);if(!existing)state.loans.unshift(loan);
    if(d.moveFunds&&!existing?.funded){const movement=d.direction==='owed'?-amount:amount;wallet.balance+=movement;state.transactions.unshift({id:crypto.randomUUID(),type:movement<0?'expense':'income',title:`Loan · ${loan.person}`,amount:movement,walletId:wallet.id,wallet:wallet.name,category:'Loans',isoDate:data.date,time:'12:00',loanId:loan.id,note:data.note})}
    save();editRecord=null;formDialog.close();render();toastMsg('Loan saved');return;
  }
  return interestBaseSubmit(e);
};
loanPage=function(){let owed=state.loans.filter(x=>x.direction==='owed'&&!x.settled).reduce((a,x)=>a+ +x.amount,0),owe=state.loans.filter(x=>x.direction==='owe'&&!x.settled).reduce((a,x)=>a+ +x.amount,0);return `<section><div class="page-head"><div><h2>Loans</h2><p>Track money owed to you and money you owe.</p></div><button class="primary-btn" data-enhance-form="loan">Add loan</button></div><div class="cashflow-stats card loan-totals"><div><span>Owed to you</span><strong>${cash(owed)}</strong></div><div><span>You owe</span><strong>${cash(owe)}</strong></div></div><div class="loan-list">${state.loans.length?state.loans.map(l=>`<div class="card loan-item"><div class="tx-icon">${svg('loan')}</div><div><strong>${escC(l.person)}</strong><small>${l.direction==='owed'?'Owes you':'You owe'} · ${escC(state.wallets.find(w=>w.id===l.walletId)?.name||'No wallet')}${l.funded?' · Wallet recorded':''}${l.note?` · ${escC(l.note)}`:''}</small></div><strong>${cash(l.amount)}</strong><span>${l.settled?'Settled':'Open'}</span><button class="text-btn" data-loan-edit="${l.id}">Edit</button><button class="text-btn" data-loan-payment="${l.id}">${l.settled?'Reopen':'Settle'}</button></div>`).join(''):'<div class="card empty">No loans yet</div>'}</div></section>`};
document.addEventListener('click',e=>{const b=e.target.closest('[data-open],[data-interest-wallet],[data-loan-payment]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();if(b.dataset.open){if(b.dataset.open==='transfer'&&location.hash==='#wallet-detail'&&selectedWallet){enhanceForm('transfer');const from=formFields.querySelector('[name="from"]');if(from)from.value=selectedWallet}else openForm(b.dataset.open)}else if(b.dataset.interestWallet)enhanceForm('interest',b.dataset.interestWallet);else if(b.dataset.loanPayment){const l=state.loans.find(x=>x.id===b.dataset.loanPayment);if(!l)return;if(l.settled){l.settled=false;save();render();return}const w=state.wallets.find(x=>x.id===l.walletId);if(!w){l.settled=true;save();render();toastMsg('Loan settled without wallet movement');return}const movement=l.direction==='owed'?+l.amount:-l.amount;if(movement<0&&w.balance<Math.abs(movement))return toastMsg('Not enough balance in the related wallet');w.balance+=movement;l.settled=true;state.transactions.unshift({id:crypto.randomUUID(),type:movement<0?'expense':'income',title:`Loan settlement · ${l.person}`,amount:movement,walletId:w.id,wallet:w.name,category:'Loans',isoDate:currentDay(),time:new Date().toTimeString().slice(0,5),loanId:l.id});save();render();toastMsg('Loan settled and wallet updated')}},true);
document.addEventListener('change',e=>{if(e.target.name==='walletLayout'){state.walletLayout=e.target.value;state.walletCompact=e.target.value==='line';save();render()}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)applyWalletInterest()});
applyWalletInterest();render();
// A settled loan is final in this simple ledger; this prevents a second settlement credit/debit.
const loanPageWithoutReopen=loanPage;
loanPage=function(){return loanPageWithoutReopen().replace(/<button class="text-btn" data-loan-payment="[^"]+">Reopen<\/button>/g,'')};
render();
